site_name: AR Paper Reading
site_url: https://belindanju.github.io/AR-paper-readings/

repo_url: https://github.com/belindanju/AR-paper-readings
repo_name: AR-paper-readings
edit_uri: ./edit/main/docs

copyright: Copyright &copy; 2022 Tian Guo


nav: 
  - Home: index.md
  - Benchmarks: 
    - ILLIXR: benchmarks/Huzaifa2020-hd.md
  - Datasets: 
    - MVImgNet: datasets/Yu2023-oz.md 
  

theme:
  name: material
  custom_dir: overrides

  logo: images/CAKE.jpg

  features: 
    - navigation.tracking
    - header.autohide
    - navigation.top
  
  palette:
      # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      lang: ja
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/belindanju
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gtbelinda
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tian-guo-21869421/
    - icon: google-scholar
      link: https://scholar.google.com/citations?user=vDzUD84AAAAJ&hl=en
  analytics:
    provider: google
    property: G-Q2V75222NL
  homepage: https://cake.wpi.edu